# permissions for end users to edit applicationprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationprofile-editor-role
rules:
- apiGroups:
  - apic.aci.cisco
  resources:
  - applicationprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apic.aci.cisco
  resources:
  - applicationprofiles/status
  verbs:
  - get
