# permissions for end users to view applicationprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationprofile-viewer-role
rules:
- apiGroups:
  - apic.aci.cisco
  resources:
  - applicationprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apic.aci.cisco
  resources:
  - applicationprofiles/status
  verbs:
  - get
