apiVersion: apic.aci.cisco/v1alpha1
kind: SegmentationPolicy
metadata:
  name: segpol1
spec:
  namespaces:
    - ns1
    - ns2
  rules:
    - eth: ip
      ip: tcp
      port: 80
    - eth: ip
      ip: tcp
      port: 443
---
apiVersion: apic.aci.cisco/v1alpha1
kind: SegmentationPolicy
metadata:
  name: segpol2
spec:
  namespaces:
    - ns2
    - ns3
    - ns4
  rules:
    - eth: ip
      ip: tcp
      port: 443 

