apiVersion: apic.aci.cisco/v1alpha1
kind: SegmentationPolicy
metadata:
  name: segmentationpolicy-sample
spec:
  name: segpol1
  tenant: k8s-tenant
  namespaces:
    - ns1
    - ns2
    - ns3
  rules:
    - eth: ip
      ip: tcp
      port: 80
    - eth: arp
    - eth: ip
      ip: udp
      port: 53