# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).
#
name: Release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        id: checkout-code
        uses: actions/checkout@master

      - name: Go Format
        run: |
          make fmt

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
    - lint
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
        id: go

      - name: Cache go mod
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Kubebuilder
        id: install-kubebuilder
        run:  |
          curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)
          chmod +x kubebuilder && mv kubebuilder /usr/local/bin/

      - name: Checkout to repository
        id: checkout-code
        uses: actions/checkout@master

      - name: Run tests
        id: test-code
        run: make test
  
  release:
    name: Release Tag
    runs-on: ubuntu-latest
    needs:
    - test
    - lint
    steps:
      - name: Checkout to repository
        id: checkout-code
        uses: actions/checkout@master

      - name: Log into registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: docker.io
          username: jgomezve
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}


      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.repository }}:${{ env.RELEASE_VERSION }}
  
  notification:
    name: Notify
    runs-on: ubuntu-latest
    if: always()
    needs:
     - release
    steps:
      - name: Webex Notification
        if: always()
        uses: qsnyder/action-wxt@master
        env:
          TOKEN: ${{ secrets.WEBEX_TOKEN }}
          ROOMID: ${{ secrets.WEBEX_ROOM_ID }}
          MESSAGE: |
            [**[${{ needs.release.result }}] ${{ github.repository }} #${{ github.run_number }}**](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            * Commit: [${{ github.event.head_commit.message }}](${{ github.event.head_commit.url }})[${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
            * Author: ${{ github.event.sender.login }}
            * Branch: ${{ github.ref }} ${{ github.head_ref }}
            * Event: ${{ github.event_name }}