name: Test

on:
  push:
    paths-ignore:
      - '*.md'

  pull_request:
    branches: [ master ]
    types: [opened, edited, reopened, synchronize]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
        id: go

      - name: Cache go mod
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Kubebuilder
        id: install-kubebuilder
        run:  |
          curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)
          chmod +x kubebuilder && mv kubebuilder /usr/local/bin/

      - name: Checkout to repository
        id: checkout-code
        uses: actions/checkout@master

      - name: Go Format
        run: |
          make fmt

      - name: Run tests
        id: test-code
        run: make test